services:
  bitkoop-validator:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - PORT=${PORT:-8000}
      - DATABASE_URL=sqlite:///data/bitkoop.db
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - WALLET_PATH=${WALLET_PATH:-~/.bittensor/wallets/}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-finney}
      - ENV=${ENV:-test}
      - RECHECK_INTERVAL=${RECHECK_INTERVAL:-P1DT0H0M0S}
      - RESUBMIT_INTERVAL=${RESUBMIT_INTERVAL:-P1DT0H0M0S}
      - TLSN_VERIFIER_URL=${TLSN_VERIFIER_URL:-http://tlsn-http-verifier:8080/verify}
    volumes:
      - ~/.bittensor:/root/.bittensor
      - ./data:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]

  tlsn-http-verifier:
    image: ghcr.io/bitkooplabs/bitkoop-tlsn-http-verifier:latest
    environment:
      - ADDR=0.0.0.0:8080
      - PRODUCTION=1
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    command: --interval 30